version: "3.7"
services:
    # redis:
    #     image: redis:alpine
    #     command: redis-server --port 6379
    #     container_name: omakase-redis
    #     hostname: omakase
    #     restart: always
    #     labels:
    #         - "name=redis"
    #         - "mode=standalone"
    #     ports:
    #         - 6379:6379
    mysql:
        image: mysql:8
        container_name: ${DB_CONTAINER_NAME}
        restart: always
        cap_add:
            - SYS_NICE
        ports:
            - 3309:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            TZ: Asia/Seoul
        # env_file:
        #     - .env
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --default-authentication-plugin=mysql_native_password
            - --sql-mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
        volumes:
            - ./dbdata:/var/lib/mysql
    node:
        container_name: omakase-server
        build:
            context: ./
        restart: always
        command: npm run start
        ports:
            - 3000:${PORT}
        depends_on:
            - mysql
        env_file:
            - .env
        volumes:
            - ./logs:/app/logs
